---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "umitransfer_external"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::umi-transfer=1.5.0"
